name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull-request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deploymnt_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: build backend
        run: yarn build:server
      - name: build frontend
        run: yarn build:ui
      - name: jest testing
        env:
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: yarn test:jest
      - name: component testing
        run: yarn test:component