name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull-request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deploymnt_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: test
        env:
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: yarn test