name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull-request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: jest testing
        env:
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          PORT: ${{ secrets.PORT }}
          SECRET: ${{ secrets.SECRET }}
        run: npm run test:jest
      - name: component testing
        run: npm run test:component
      - name: end-to-end testing
        uses: cypress-io/github-action@v2
        env:
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          SECRET: ${{ secrets.SECRET }}
          PORT: ${{ secrets.PORT }}
        with:
          env: true
          command: npm run test:e2e
          start: npm run start:cypress
          wait-on: http://localhost:3000
      - name: install doctl (digitalocean deployment tool)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: deploy on digitalocean
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}